colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  copyright = "Â© 2024 FreshSpin Laundry | Designed by [Crafted Edge Solutions](https://craftededgesolutions.com)"

  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&q=80&w=1200"
  showRecent = true
  showRecentItems = 3
  cardView = true

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "big"
  showReadingTime = true
  showWordCount = true
  sharingLinks = ["linkedin", "twitter", "whatsapp", "facebook", "email"]
