colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
sharingLinks = ["whatsapp", "email"]
copyright = "Â© 2026 FreshSpin Laundry | Designed by [**Crafted Edge Solutions**](https://meshack-vs-you-all.github.io/crafted-edge-solutions-hg/) | Lead Developer [**Meshack**](https://meshack-vs-you-all.github.io/meshack-hugo-portfolio/)"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true

  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&q=80&w=1200"
  showRecent = true
  showRecentItems = 3
  cardView = true
  cardShadow = false
  cardBorder = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "big"
  showReadingTime = true
  showWordCount = true
